// <auto-generated />
using AudiSoft.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AudiSoft.Infrastructure.Migrations
{
    [DbContext(typeof(AudiSoftDbContext))]
    [Migration("20260821051121_InicialConSeed")]
    partial class InicialConSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AudiSoft.Domain.Entities.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Estudiantes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Juan Pérez"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "María Gómez"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Carlos Rodríguez"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Ana Martínez"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Luis Fernández"
                        });
                });

            modelBuilder.Entity("AudiSoft.Domain.Entities.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int");

                    b.Property<int>("IdProfesor")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdEstudiante");

                    b.HasIndex("IdProfesor");

                    b.ToTable("Notas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdEstudiante = 1,
                            IdProfesor = 1,
                            Nombre = "Parcial 1",
                            Valor = 3.5m
                        },
                        new
                        {
                            Id = 2,
                            IdEstudiante = 2,
                            IdProfesor = 2,
                            Nombre = "Parcial 2",
                            Valor = 4.2m
                        },
                        new
                        {
                            Id = 3,
                            IdEstudiante = 3,
                            IdProfesor = 3,
                            Nombre = "Quiz 1",
                            Valor = 2.8m
                        },
                        new
                        {
                            Id = 4,
                            IdEstudiante = 4,
                            IdProfesor = 1,
                            Nombre = "Proyecto Final",
                            Valor = 4.9m
                        },
                        new
                        {
                            Id = 5,
                            IdEstudiante = 5,
                            IdProfesor = 2,
                            Nombre = "Examen Final",
                            Valor = 3.0m
                        });
                });

            modelBuilder.Entity("AudiSoft.Domain.Entities.Profesor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Profesores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Andrés Torres"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Beatriz Ramírez"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Camilo Vargas"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Diana Castro"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Eduardo Salazar"
                        });
                });

            modelBuilder.Entity("AudiSoft.Domain.Entities.Nota", b =>
                {
                    b.HasOne("AudiSoft.Domain.Entities.Estudiante", "Estudiante")
                        .WithMany("Notas")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AudiSoft.Domain.Entities.Profesor", "Profesor")
                        .WithMany("Notas")
                        .HasForeignKey("IdProfesor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("AudiSoft.Domain.Entities.Estudiante", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("AudiSoft.Domain.Entities.Profesor", b =>
                {
                    b.Navigation("Notas");
                });
#pragma warning restore 612, 618
        }
    }
}
